### PR TITLE
Update installation

### PR DESCRIPTION
**Pull request by CHrlS98**
Installation would crash with allensdk 2.15 because of an error coming from the `statsmodel` dependency. 
 1. Updated allensdk to 2.16. 
 2. Once fixed, script execution would still fail because of some deprecated functions from setuptools. 
 3. Fixed by making some changes to the installation script. 
 4. Installation and scripts now work!

### CODE REVIEW

**Comment by FIrgolitsch** [comment]
I would recommend removing all the specific versions from the setup file unless there is a good reason why we would want a version. With the amount of dependencies we have it's better to let pip's or conda's dependency resolver figure out what works together. I have been using this for the liom-toolkit and it has been working much better for me since.

**Comment by CHrlS98** [comment]
I get it but it's probably more reproducible if we find a set of package versions which work well together and then enforce it for all users, no?

**Comment by FIrgolitsch** [comment]
The problem with that is that we limit our package to only work with itself. If the user wants to use any other package in conjunction with ours we might create many problems in that environment. This is a massive problem when working with the Allen SDK for example, as they enforce many of those requirements. In my opinion, reproducibility comes from publishing the versions of all the packages in the environment when the analysis is run. There are many factors that influence reproducibility (system architecture, python version, etc.), and I don't think that should be our concern when making these tools available to the public.

**Comment by CHrlS98** [comment]
I get it but I think we at least need a range of versions. There are functions that existed in some older `scipy` or `numpy` versions which may not exist anymore or vice versa and we at least need to install versions for which we expect the library to work for everyone.

**Comment by FIrgolitsch** [comment]
Yeah! That's what I meant with having a good reason for it. If we know we are using things that either disappeared or are changed a lot we should fix those to a minimum or maximum version. I just think we should do that sparingly.

**Review by joe-from-mtl — COMMENTED** [review]
We modified the way the tool is installed in the linumpy-private repo. We are now using pyproject.toml and we removed many dependencies that were not necessary. We should follow that structure instead of the setup.py.

**Comment by CHrlS98** [comment]
Yeah I saw, but what I dislike is that using `pyproject.toml` it's not possible to automatically detect the scripts in `scripts` folder. I however have a fix for this which consists of using a minimal `pyproject.toml` file and then keeping most of the stuff in `setup.py`. I'll close the PR for now and maybe open a new one in the private repo at a later date.

I'll close this PR for now.

**Comment by FIrgolitsch** [comment]
Considering setup.py is getting deprecated I think we should move to the toml files. I feel not being able to detect scripts automatically is more of a feature than a bug as it enhances security by limiting script exposure. You only need to add them once anyway, and if we automatically want to create the list of scripts to use in the file we could just call something like `find scripts -type f > scripts.txt`.

**Comment by CHrlS98** [comment]
It's not being deprecated, see here: https://packaging.python.org/en/latest/discussions/setup-py-deprecated/

It's running `python setup.py` directly which is deprecated.

**Comment by FIrgolitsch** [comment]
Good to know! I thought it was the whole thing. I think the combination of the setup.py and toml files might be a good idea then.

**Pull request closed without merging**
