### PR TITLE
[WIP] Migrate PSF and attenuation correction

### PR DESCRIPTION
**Pull request by CHrlS98**
This PR goes on top of PR #19 . It ports scripts from the `sbh-reconstruction` repository for compensating for the signal depth dependence and for signal attenuation.

I am not sure it works as expected. This is the attenuation map for a sagittal slice...
image

... and here is the corresponding attenuation-corrected slice:
image

### CODE REVIEW

**Comment by CHrlS98** [comment]
### An update 
I made some changes both to the PSF compensation method and to the attenuation correction (now using the extended Vermeer model). I also played with the parameters a little bit and here is my updated attenuation compensated dataset. 

Looks way better.

image

**Comment by joe-from-mtl** [comment]
Was the PSF correction applied before estimating and compensating the attenuation? After the those steps, the intensity depth profile in agarose should be flat, but it seems to follow a gaussian profile in the second example. 

image

**Comment by CHrlS98** [comment]
@joe-from-mtl 
> Was the PSF correction applied before estimating and compensating the attenuation?

Yes it was but it's possible the default parameters do not work for the new system. From what I understand `z_r` seems to depend on the objective used. From my experience with implementing the PSF estimation method myself, the fitting method is also very sensitive to noise and will very easily converge towards a wrong set of values.

**Comment by joe-from-mtl** [comment]
We need to improve the robustness of the psf and attenuation estimation methods in homogeneous areas. One way could be to simplify the estimation any doing some transforms (ex. Log to convert the exponential decay into linear decay) and using data derived psf profile instead of model based (ex using BaSIC). I'll think about this and come back to you

**Comment by CHrlS98** [comment]
@joe-from-mtl

> Was the PSF correction applied before estimating and compensating the attenuation? After the those steps, the intensity depth profile in agarose should be flat, but it seems to follow a gaussian profile in the second example.
> image

Also keep in mind that the voxels you are investigating here are not agarose voxel but background padding voxels which do not have a PSF. As such it is possible that the method overcompensates for these voxels (the data is not masked).

**Comment by CHrlS98** [comment]
See #33

**Pull request closed without merging**
